env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  "import/prefer-default-export": 0
  "import/extensions": 0
  "import/no-unresolved": 0
  no-plusplus: 0
  no-underscore-dangle: 0
  no-return-assign: 0
  "prettier/prettier":
    - "error"
  no-tabs: off
  indent: off
  operator-linebreak: off
  no-bitwise: off
  no-param-reassign: off
  'react/jsx-indent': off

